using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ModernClinic
{
    public partial class MainMenu : Form
       
    {
        private string tenNV;
        SqlConnection conn;
        SqlCommand command, sumCM;
        SqlDataAdapter adaptear = new SqlDataAdapter();
        DataTable DataTable = new DataTable();
        Int32 SumPatien;
        string ID;
        void Loadd()
        {
            command = conn.CreateCommand();
            command.CommandText = "select *  from BENHNHAN WHERE TrangThai != N'Đã Khám' and NgayKham = (SELECT CAST( GETDATE() AS Date ) );";
            adaptear.SelectCommand = command;
            DataTable.Clear();
            adaptear.Fill(DataTable);
            dataGridtblBenhNhan.DataSource = DataTable;
            sumCM = conn.CreateCommand();
            sumCM.CommandText = "SELECT count(*) from BENHNHAN";
            SumPatien = (Int32) sumCM.ExecuteScalar();
            txtSum.Text = "Tổng Bệnh Nhân: "+ SumPatien.ToString();
        }
        void ShiftStaff(string username)
        {
            conn.Open();
            string checkLG_string = "Select HoTen from NHANVIEN where Username = '" + username + "'";
            SqlCommand cmd = new SqlCommand(checkLG_string, conn);
            SqlDataReader check = cmd.ExecuteReader();
            string role = check[0].ToString();
            AccountName.Text = role + " (Thoát)";

        }
        public MainMenu()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            cbbGender.Properties.Items.Add("Nam");
            cbbGender.Properties.Items.Add("Nữ");

        }
        class BenhNhan
        {
            int iD;
            String hoTen;
            int namSinh;
            String diaChi;
            DateTime ngayKham;
            String trieuChung;
            String trangThai;

            public BenhNhan(int iD, string hoTen, int namSinh, string diaChi, DateTime ngayKham, string trieuChung, string trangThai)
            {
                this.ID = iD;
                this.HoTen = hoTen;
                this.NamSinh = namSinh;
                this.DiaChi = diaChi;
                this.NgayKham = ngayKham;
                this.TrieuChung = trieuChung;
                this.TrangThai = trangThai;
            }

            public int ID { get => iD; set => iD = value; }
            public string HoTen { get => hoTen; set => hoTen = value; }
            public int NamSinh { get => namSinh; set => namSinh = value; }
            public string DiaChi { get => diaChi; set => diaChi = value; }
            public DateTime NgayKham { get => ngayKham; set => ngayKham = value; }
            public string TrieuChung { get => trieuChung; set => trieuChung = value; }
            public string TrangThai { get => trangThai; set => trangThai = value; }
        }

       
            //  SQLconnection
            //  SQLconnection
            string query = "select * from BENHNHAN";
            DataSet data = new DataSet();

        public string TenNV { get => tenNV; set => tenNV = value; }
       

        void loadData()
            {
                using (SqlConnection connection = new SqlConnection(DataConnection.connectionString))
                {
                    connection.Open();
                    SqlDataAdapter adapter = new SqlDataAdapter(query, connection);
                    DataTable table = new DataTable();
                    adapter.Fill(table);
                    dataGridtblBenhNhan.DataSource = table;
                    connection.Close();
                }
            }

            //SQLcommand
            //SQLAdapter

        private void MainMenu_Load(object sender, EventArgs e)
        {
            loadData();
           
        }

        private void dataGridtblBenhNhan_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            
            int i = dataGridtblBenhNhan.CurrentRow.Index;
            txtName.Text = dataGridtblBenhNhan.Rows[i].Cells[1].Value.ToString();
            cbbGender.Text = checkGender((Boolean)dataGridtblBenhNhan.Rows[i].Cells[2].Value);
            txtNamSinh.Text = dataGridtblBenhNhan.Rows[i].Cells[3].Value.ToString();
            txrAddress.Text = dataGridtblBenhNhan.Rows[i].Cells[4].Value.ToString();
            DateTime temp = (DateTime)dataGridtblBenhNhan.Rows[i].Cells[5].Value;
            dateCome.Text = temp.ToShortDateString();
            txtChanDoan.Text = dataGridtblBenhNhan.Rows[i].Cells[6].Value.ToString();    
            ID = dataGridtblBenhNhan.Rows[i].Cells[0].Value.ToString();
        }
     private String checkGender(Boolean gender)
        {
            if (gender)
                return "Nam";
            else
                return "Nu";
        }
        private int  checkGender(String gender)
        {
            if (gender.Equals("Nam"))
                return 1;
            else
                return 0;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            conn = new SqlConnection(DataConnection.connectionString);
            conn.Open();
            command = conn.CreateCommand();
            int namsinh = Int32.Parse(txtNamSinh.Text);
            DateTime date = DateTime.Today;
            String arr= "insert into BENHNHAN (HoTen, GioiTinh, NamSinh,DiaChi,NgayKham, TrieuChung, TrangThai) VALUES (N'" + txtName.Text + "',N'" + checkGender(cbbGender.Text) + "','" + namsinh + "',N'" + txrAddress.Text + "','" + date + "',N'" + txtChanDoan.Text + "',N'" + "Chờ Khám" + "')";
            command.CommandText = arr;

            // command.CommandText = "insert into BENHNHAN (HoTen, GioiTinh, NamSinh,DiaChi,NgayKham, TrieuChung, TrangThai) VALUES ('"+txtName.Text+"','"+cbbGender.Text+ "','" + namsinh + "','" + txrAddress.Text + "','" + dateCome.Text + "','" + txtChanDoan.Text + "','"+"Chờ Khám"+"')'";
            command.ExecuteNonQuery();
            Loadd();
         
          
        }

        private void AccountName_Click(object sender, EventArgs e)
        {
            this.Close();
            Login login = new Login();
            login.Show();
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            conn = new SqlConnection(DataConnection.connectionString);
            conn.Open();
            command = conn.CreateCommand();
            
            // String arr = "delete from BENHNHAN WHERE HoTen = N'" + txtName.Text+"'";
            String arr = "delete from BENHNHAN WHERE MaBenhNhan = " + ID ;
            String Request_delete = "Update BENHNHAN SET TrangThai = N'Chờ xoá' where MaBenhNhan = " +ID;

            // command.CommandText = arr;
            command.CommandText = Request_delete;
            // command.CommandText = "insert into BENHNHAN (HoTen, GioiTinh, NamSinh,DiaChi,NgayKham, TrieuChung, TrangThai) VALUES ('"+txtName.Text+"','"+cbbGender.Text+ "','" + namsinh + "','" + txrAddress.Text + "','" + dateCome.Text + "','" + txtChanDoan.Text + "','"+"Chờ Khám"+"')'";
            command.ExecuteNonQuery();
            Loadd();
        }


    }
}
